Task 1: Create A REST API With JSON Server
milothea/AngulatJS-Advanced pull request #1
Opened 2022-02-18 21:04 UTC by milothea

* Add required npm packages

* Create data base at db.json

* Initialize Angular project

2022-03-28 13:07 UTC, Jaskon commented
I can't see this part of the task

![image](https://user-images.githubusercontent.com/18248628/160404176-a292a3b0-d96b-40e5-a81f-f2bbf762f4f5.png)

2022-03-28 13:07 UTC, Jaskon requested changes
I can't see this part of the task

![image](https://user-images.githubusercontent.com/18248628/160404391-dc2c90b5-577a-4526-aed7-6376cd78da83.png)

2022-03-28 18:41 UTC, milothea commented
Resolved according to comment

2022-03-29 10:32 UTC, Jaskon approved these changes

2022-03-29 15:50 UTC, merged